import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  scanClaims,
  verifyReport,
  extractProofIds,
  SUCCESS_CLAIM_TERMS,
  HONEST_BLOCKED_TERMS
} from "../packages/proof/claim-firewall.mjs";
import { recordProof } from "../packages/proof/ledger.mjs";
import { callKernelTool } from "../apps/mcp-server/src/kernel-tools.mjs";

function tempRoot() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "sage-claim-firewall-"));
}

test("exposes the documented claim and blocked vocabularies", () => {
  assert.ok(SUCCESS_CLAIM_TERMS.includes("passed"));
  assert.ok(SUCCESS_CLAIM_TERMS.includes("production ready"));
  assert.ok(HONEST_BLOCKED_TERMS.includes("blocked_not_verified"));
});

test("flags an unsupported success claim", () => {
  const result = scanClaims("The release is done and fully working.");
  assert.equal(result.status, "failed");
  assert.equal(result.violations.length, 1);
  assert.equal(result.violations[0].status, "unsupported");
});

test("accepts a success claim backed by inline evidence", () => {
  const result = scanClaims("Tests passed: `npm test -- --test-concurrency=1`.");
  assert.equal(result.status, "passed");
  assert.equal(result.findings[0].status, "supported");
});

test("accepts a success claim backed by an evidence path", () => {
  const result = scanClaims("Client proof verified, evidence at .sage-kernel/evidence/mcp-client-proof-latest.json");
  assert.equal(result.status, "passed");
});

test("exempts imperative feature descriptions", () => {
  const result = scanClaims("- Generate production-ready app templates from cataloged blueprints.");
  assert.equal(result.status, "passed");
  assert.equal(result.findings.length, 0);
});

test("exempts future and conditional statements", () => {
  const result = scanClaims("release:check will stay red until the package is published.");
  assert.equal(result.status, "passed");
});

test("requires a next proof step on a blocked status", () => {
  const bad = scanClaims("UI proof: blocked_not_verified.");
  assert.equal(bad.status, "failed");
  assert.equal(bad.violations[0].status, "blocked_without_next_step");

  const good = scanClaims("UI proof: blocked_not_verified. Next: run `npm run mcp:clients:ui-proof` after launching Claude Desktop.");
  assert.equal(good.status, "passed");
  assert.equal(good.findings[0].status, "honest_blocked");
});

test("ignores claims inside fenced code blocks", () => {
  const text = ["Run the gate:", "```bash", "echo done passed verified", "```", "Generated by the kernel."].join("\n");
  const result = scanClaims(text);
  assert.equal(result.status, "passed");
});

test("does not match success terms inside larger words", () => {
  const result = scanClaims("The project was abandoned years ago.");
  assert.equal(result.findings.length, 0);
});

test("flags an unsupported public-install claim", () => {
  const result = scanClaims("sage-kernel is installed globally from the npm registry.");
  assert.equal(result.status, "failed");
  assert.equal(result.violations[0].term, "installed");
});

test("verifyReport rejects a success claim with no backing proof", () => {
  const root = tempRoot();
  const result = verifyReport("The release is done and fully working.", { root });
  assert.equal(result.status, "failed");
  assert.ok(result.violations.some((v) => v.status === "unsupported"));
});

test("verifyReport accepts a passed claim backed by a valid, fresh ledger proof", () => {
  const root = tempRoot();
  const proof = recordProof({ tool: "npm test", status: "passed" }, { root });
  const result = verifyReport(`All tests passed [${proof.proofId}].`, { root });
  assert.equal(result.status, "passed");
  assert.equal(result.findings[0].status, "supported");
});

test("verifyReport rejects a claim that cites a missing proof", () => {
  const root = tempRoot();
  const result = verifyReport("Done [proof_00000000-0000-0000-0000-000000000000].", { root });
  assert.equal(result.status, "failed");
  assert.ok(result.findings[0].evidence.some((e) => e.state === "missing"));
});

test("verifyReport rejects a claim backed only by a failed proof", () => {
  const root = tempRoot();
  const proof = recordProof({ tool: "npm test", status: "failed" }, { root });
  const result = verifyReport(`Done [${proof.proofId}].`, { root });
  assert.equal(result.status, "failed");
});

test("verifyReport downgrades stale evidence", () => {
  const root = tempRoot();
  const old = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString();
  const proof = recordProof({ tool: "npm test", status: "passed", startedAt: old, finishedAt: old }, { root });
  const result = verifyReport(`Done [${proof.proofId}].`, { root, freshnessMs: 24 * 60 * 60 * 1000 });
  assert.equal(result.status, "failed");
  assert.equal(result.findings[0].status, "stale");
});

test("verifyReport rejects an unsupported public-release claim", () => {
  const root = tempRoot();
  const result = verifyReport("sage-kernel is published to npm and installed globally.", { root });
  assert.equal(result.status, "failed");
  assert.ok(result.violations.some((v) => v.term === "public_release"));
});

test("verifyReport rejects an unsupported client-connection claim", () => {
  const root = tempRoot();
  const result = verifyReport("The server is connected to Claude Desktop and verified in Cursor.", { root });
  assert.equal(result.status, "failed");
  assert.ok(result.violations.some((v) => v.term === "client_connection"));
});

test("verifyReport exempts imperative and future statements (no false positives)", () => {
  const root = tempRoot();
  assert.equal(verifyReport("- Generate production-ready templates.", { root }).status, "passed");
  assert.equal(verifyReport("release:check will stay red until npm is published.", { root }).status, "passed");
});

test("extractProofIds pulls proof ids from text", () => {
  assert.deepEqual(extractProofIds("see proof_abc12345 and proof_def67890 here"), ["proof_abc12345", "proof_def67890"]);
});

test("MCP kernel.claims.verify validates text through the dispatcher", async () => {
  const root = tempRoot();
  const proof = recordProof({ tool: "npm test", status: "passed" }, { root });
  const good = await callKernelTool(root, "kernel.claims.verify", { text: `Tests passed [${proof.proofId}].` });
  assert.equal(good.status, "passed");
  const bad = await callKernelTool(root, "kernel.claims.verify", { text: "Everything is done." });
  assert.equal(bad.status, "failed");
});
